# Generated by Django 2.1.7 on 2019-11-14 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=336)),
                ('date_of_birth', models.DateField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('department', models.CharField(choices=[('IT', 'it'), ('HR', 'hr'), ('FINANCE', 'finance')], default='IT', max_length=255)),
                ('resume', models.FileField(blank=True, null=True, upload_to='CVs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])])),
            ],
        ),
    ]
